### ISSUE TITLE
String variables show "incorrect" current value

### ISSUE THREAD

**Issue by Electroprint** [aphyt/aphytcomm#1] opened 2023-12-19 14:43 UTC
When using ".read_variable" from an Omron NX PLC for a variable that contains a string it shows the current data in the string variable but also any previous data that was there previously. 

For example a string variable on the PLC contains "ABC1234".

I change the variable to contain "Z".

When i view it on the PLC it confirms that it only contains "Z".

But when i use ".read_variable" it shows the variable as containing "ZC1234"

As it shows two characters changed I'm thinking that the PLC may possibly do something like put the new data in the string then put a null character at the end and leaves the rest of the data there but stops reading after null characters.

Could this be the case and is it possible to only read the data that the PLC see's in the variable?

Thank you.

**Comment by aphyt** [comment] 2023-12-19 15:33
I am unable to reproduce. Can you confirm that you are using the latest version from either GitHub or PyPi? When I use this test script:

``` Python
from aphyt import omron
import time

fake_eip_instance = omron.n_series.NSeries()
fake_eip_instance.connect_explicit('192.168.250.9')
fake_eip_instance.register_session()

while True:
    cip_string = fake_eip_instance.read_variable('TestString')
    print(cip_string)
    fake_eip_instance.write_variable('TestString', 'Z')
    time.sleep(2)
    cip_string = fake_eip_instance.read_variable('TestString')
    print(cip_string)
    fake_eip_instance.write_variable('TestString', 'ABC1234')
    time.sleep(2)
```

I receive the expected response of:

```
ABC1234
Z
ABC1234
Z
ABC1234
Z
ABC1234
```

Repeating. I see the same values alternating in Sysmac Studio. I also tested by reading repeatedly and changing the ABC1234 to Z on the PLC and the library picks up the change as expected.

**Comment by Electroprint** [comment] 2023-12-19 17:00
Thanks for your quick reply and looking into this.

I have checked and have the latest version 0.1.17 

I have done some further testing and found specifically when it happens.

Using your library i have found that if i use "read_variable" method and then adjust the value in Sysmac Studio using a Watch Tab Page then it works exactly as expected going from "ABC1234" to "Z" as you say.

But in Sysmac Studio if i use the "MOVE" function in the PLC ladder to move "Z" into the string variable then it shows up as "Z" on the PLC but "ZC1234" when using the "read_variable" method in your library.

I'm not sure why this would be.

**Comment by aphyt** [comment] 2023-12-19 17:18
That makes sense to me, as the MOVE instruction is just a raw memory copy instruction, so the Z and Null are overwriting the first two characters, but leaving everything else. One strategy I have seen is keeping a constant blank string of the same size as your current string and writing that before you write the new value with MOVE. I'm going to go ahead and close this.

**Closed by aphyt** 2023-12-19 17:18 UTC
Labels: question

**Comment by Electroprint** [comment] 2023-12-20 09:39
Would it be possible for your library to be able to check for Null and only show the data before this?

I have tried in the PLC program to get it to overwrite all the data with Null in a string but there doesn't seem to be any sensible way to do it. I've tried the "Delete", "Move" and "Exchange" function blocks with and without null strings as inputs and it only ever puts in one Null and leaves the rest of the data there. Even when i do a "Delete" for all characters but the last one in a string it just moves the last one to the front of the string, puts a Null after it and leaves the rest of the data. So it seems there is no sensible way to do this from the PLC program that i can see unfortunately.

If you do any future updates it would be great if you could include this so it filters the data to take this into account.

Thanks again.

**Comment by aphyt** [comment] 2023-12-20 17:47
I agree there is no easy way to do this in the PLC and I will change the default behavior to split at the null and only return the first string, as that would be the most expected behavior. I don't like the idea of throwing away data that comes from the controller, but I guess if a programmer really wanted the raw data they could still grab it from the raw bytes in the CIPString object.

I plan a new release shortly, so it should be fixed in the next day or two and you should be able to upgrade.

**Comment by aphyt** [comment] 2023-12-20 18:42
I have merged the requested change and updated to version 0.1.18 on both Git and PyPi.

**Comment by Electroprint** [comment] 2023-12-21 08:41
Excellent I've got it now. Thanks for that.
